quarkus:
  flyway:
    migrate-at-start: true
  http:
    port: 8080
    test-port: 8081
    read-timeout: 60s
  datasource:
    db-kind: postgresql
    username: dolap
    password: 123456
    jdbc:
      url: jdbc:postgresql://localhost:5409/quarkus-ddd
  hibernate-orm:
    database:
      generation: validate
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} - RequestId: %X{requestId} - %-5p [%c{3.}] (%t) %s%e%n"