version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - env/local-database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5406:5432"
volumes:
  database-data: